search_terms:
        - criminal
        - crime
        - curfew
        - blm
        - black lives matter
        - police
        - protest
        - riot
        - breonna taylor
        - george floyd
        - cop
        - loot
        - liberal
        - conservative
since: 2020-05-26
until: 2020-06-09
